name: book-ci

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js (match your Angular version requirements)
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run unit tests
      - name: Run Angular tests
        # run: npm test -- --watch=false --browsers=ChromeHeadless
        run: npm run test:ci

      # 5. Build Angular app
      - name: Build Angular app
        run: npm run build --if-present
